char           =  { ASCII_ALPHANUMERIC | "." | "_" | "/" | "-" | " " }
name           = @{ char+ }
value          = @{ char* }
property       =  { name ~ "=" ~ value }
domain_section =  { "[[" ~ name ~ "]]" }
path_section   =  { "[[[" ~ name ~ "]]]" }
main_section   =  { "[" ~ name ~ "]" }


file = {
    SOI ~
    ((property | main_section | domain_section | path_section)? ~ NEWLINE)* ~
    EOI
}

