
WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

file = { super_config ~ (proxy_config | lb_config)* }

super_config = { "prometheus_addr" ~ "=" ~ string }

proxy_config = { 
    "[proxy]" ~ listener ~ tls_certificate? ~ tls_certificate_key? ~ domain+ 
}

lb_config = { 
    "[load_balancer]" ~ listener ~ health_check? ~ health_check_frequency? ~ parallel_health_check? ~ tls_certificate? ~ tls_certificate_key? ~ domain+ 
}

listener = { "listener" ~ "=" ~ string }
tls_certificate = { "tls_certificate" ~ "=" ~ string }
tls_certificate_key = { "tls_certificate_key" ~ "=" ~ string }
health_check = { "health_check" ~ "=" ~ ("true" | "false") }
health_check_frequency = { "health_check_frequency" ~ "=" ~ number }
parallel_health_check = { "parallel_health_check" ~ "=" ~ ("true" | "false") }

domain = { "[[" ~ string ~ "]]" ~ config_entry* ~ route* }

route = { "[[[" ~ string ~ "]]]" ~ config_entry* }

config_entry = { key ~ "=" ~ value }

key = { ASCII_ALPHANUMERIC+ }
value = { string | number | boolean }

string = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
number = @{ ASCII_DIGIT+ }
boolean = { "true" | "false" }

